name: Docker

on:
  schedule:
    - cron: '44 13 * * *'
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.5.0
        with:
          cosign-release: 'v2.2.4'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image for /java
      - name: Build and push Java image
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./java
          file: ./java/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:java
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:java-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Build and push Docker image for /python
      - name: Build and push Python image
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./python
          file: ./python/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:python
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:python-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push Go image
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./golang
          file: ./golang/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:go
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:go-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sign Java image
        if: github.event_name != 'pull_request'
        run: |
          cosign sign --yes ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:java
          cosign sign --yes ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:java-${{ github.sha }}

      - name: Sign Python image
        if: github.event_name != 'pull_request'
        run: |
          cosign sign --yes ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:python
          cosign sign --yes ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:python-${{ github.sha }}
      - name: Sign Golang image
        if: github.event_name != 'pull_request'
        run: |
          cosign sign --yes ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:go
          cosign sign --yes ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:go-${{ github.sha }}